"""add_tools_to_tasks

Revision ID: 865488a216fa
Revises: 16aad3cd0955
Create Date: 2026-03-17 12:29:33.530729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865488a216fa'
down_revision: Union[str, Sequence[str], None] = '16aad3cd0955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tools', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tools')
    # ### end Alembic commands ###
